tar.gz. before uploading, or github upload complans about colon in filename
 https://github.com/jmarrec/EnergyPlus/actions/runs/27832002956/job/82370826883

  Run actions/upload-artifact@v7
  With the provided path, there will be 1377 files uploaded
  Artifact name is valid!
  Root directory input is valid!
  Error: The path for one of the files in artifact is not valid: /input-output-reference/1.4-sec:api-usage.html. Contains the following character:  Colon :

  Invalid characters include:  Double quote ", Colon :, Less than <, Greater than >, Vertical bar |, Asterisk *, Question mark ?, Carriage return \r, Line feed \n

  The following characters are not allowed in files that are uploaded due to limitations with certain file systems such as NTFS. To maintain file system agnostic behavior, these characters are intentionally not allowed to prevent potential
  problems with downloads on different file systems.